# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d59f5647ff61bb03ec50f173a1a86b9075d3bf427341ebac4114448912d0695db59d605258ec9ebdd6368b3088c87c7a3dff9d024f59cb165c8f993b749b6a02

test:
  secret_key_base: 1a64686d57a1c39d266e1f360e7e1d9f0752b763760d91c9b1bc1179333a3e554aac53633b7f7d70edab3ff84b9401558a5d3e9dd7cb123e6b23540c9fa6f634

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
